// Active (toggleable) effect resolution.
//
// "Passive" boosts (Muscle Band, Rapid-Fire Scarf base, Choice Scarf, red
// emblems) are already in computeEffectiveStats via held-item stats + the red
// set bonus, so they are NOT toggles here. The toggles are the *active* combat
// states the user previews: X-Attack, Rapid-Fire Scarf proc, ally buffs, and
// the selected Pokémon's move/ability buffs, and the Theia Sky Ruins wild buff
// (Accelgor) — all default OFF.
//
// Attack-speed points come from src/data/attackSpeedBoosts.json (generated by
// tools/community/normalize_as_boosts.py). Other stat changes live in the owned
// src/data/activeEffectExtras.json so a sheet refresh cannot drop them.

import type { Pokemon, HeldItem, BattleItem, StatBlock } from "../types";
import boostsData from "../data/attackSpeedBoosts.json";
import effectExtras from "../data/activeEffectExtras.json";

export type BoostSource = "item" | "move" | "ally" | "wild";

export interface ActiveBoost {
  id: string; // unique within a loadout, e.g. "x-attack" or "move:Feint"
  label: string;
  asPoints: number; // additive attack-speed points when active
  source: BoostSource;
  perLevel?: number; // extra points per level above 1
  minLevel?: number; // available from this level
  maxLevel?: number; // available up to this level
  // Multiplicative stat buffs applied when active, e.g. X-Attack { attack: 0.2 }
  // means ×1.2. A value of 1 on a fraction stat means ×2 (Inteleon crit).
  statMultipliers?: Partial<Record<keyof StatBlock, number>>;
  // Additive stat buffs in StatBlock units. critRate 0.05 is +5 percentage
  // points. defense 300 is +300 Defense.
  statAdds?: Partial<StatBlock>;
  note?: string;
}

interface GlobalItem {
  id: string;
  label: string;
  asPoints: number;
  kind: "active" | "passive" | "ally";
}
interface MoveBoost {
  source: string;
  asPoints: number;
  perLevel?: number;
  minLevel?: number;
  maxLevel?: number;
}

interface EffectExtra {
  asPoints?: number;
  perLevel?: number;
  minLevel?: number;
  maxLevel?: number;
  statMultipliers?: Partial<Record<keyof StatBlock, number>>;
  statAdds?: Partial<StatBlock>;
  note?: string;
  label?: string;
}

const ITEM_EXTRAS = effectExtras.items as Record<string, EffectExtra>;
const MOVE_EXTRAS = effectExtras.moves as Record<string, Record<string, EffectExtra>>;
const WILD_EXTRAS = effectExtras.wild as Record<string, EffectExtra>;

const GLOBALS = boostsData.globalItems as GlobalItem[];
const MOVES = boostsData.moves as Record<string, MoveBoost[]>;

const globalById = (id: string) => GLOBALS.find((g) => g.id === id);

/** Is a level-gated boost available at this level? */
export function boostAvailableAtLevel(
  b: { minLevel?: number; maxLevel?: number },
  level: number,
): boolean {
  if (b.minLevel != null && level < b.minLevel) return false;
  if (b.maxLevel != null && level > b.maxLevel) return false;
  return true;
}

/** Points a single boost contributes at a given level (includes per-level scaling). */
export function boostPointsAtLevel(b: ActiveBoost, level: number): number {
  if (!boostAvailableAtLevel(b, level)) return 0;
  return b.asPoints + (b.perLevel ? b.perLevel * (level - 1) : 0);
}

/**
 * The toggleable active boosts relevant to a loadout: X-Attack (if that battle
 * item is equipped), RFS proc (if Rapid-Fire Scarf is held), ally buffs, Theia
 * Sky Ruins wild buff (always listed), and the selected Pokémon's move/ability
 * buffs. Default state is all-OFF.
 */
export function availableActiveBoosts(
  pokemon: Pokemon | null,
  heldItems: (HeldItem | null)[],
  battleItem: BattleItem | null,
): ActiveBoost[] {
  const out: ActiveBoost[] = [];

  if (battleItem?.id === "x-attack") {
    const g = globalById("x-attack")!;
    const extra = ITEM_EXTRAS["x-attack"];
    out.push({
      id: "x-attack",
      label: "X Attack (active)",
      asPoints: g.asPoints,
      source: "item",
      statMultipliers: extra?.statMultipliers,
      statAdds: extra?.statAdds,
      note: extra?.note ?? "+20% Attack, +20% Sp. Atk, +25% attack speed for 6s.",
    });
  }
  if (heldItems.some((i) => i?.id === "rapid-fire-scarf")) {
    const g = globalById("rapid-fire-scarf-proc")!;
    out.push({
      id: "rfs-proc",
      label: "Rapid-Fire Scarf (proc)",
      asPoints: g.asPoints,
      source: "item",
      note: "After a move: next basic attacks gain attack speed.",
    });
  }
  for (const g of GLOBALS.filter((x) => x.kind === "ally")) {
    out.push({ id: g.id, label: g.label, asPoints: g.asPoints, source: "ally" });
  }
  out.push(...wildBoosts());
  if (pokemon) out.push(...moveBoostsFor(pokemon.displayName));
  return out;
}

/** Theia Sky Ruins buff. Always offered; not written by the attack-speed sheet. */
function wildBoosts(): ActiveBoost[] {
  return Object.entries(WILD_EXTRAS).map(([id, extra]) => ({
    id,
    label: extra.label ?? id,
    asPoints: extra.asPoints ?? 0,
    source: "wild",
    perLevel: extra.perLevel,
    minLevel: extra.minLevel,
    maxLevel: extra.maxLevel,
    statMultipliers: extra.statMultipliers,
    statAdds: extra.statAdds,
    note: extra.note,
  }));
}

function withExtra(boost: ActiveBoost, extra: EffectExtra | undefined): ActiveBoost {
  if (!extra) return boost;
  return {
    ...boost,
    statMultipliers: extra.statMultipliers ?? boost.statMultipliers,
    statAdds: extra.statAdds ?? boost.statAdds,
    note: extra.note ?? boost.note,
  };
}

/** Sheet attack-speed rows, plus owned extras (including crit-only toggles). */
function moveBoostsFor(displayName: string): ActiveBoost[] {
  const extras = MOVE_EXTRAS[displayName] ?? {};
  const seen = new Set<string>();
  const out: ActiveBoost[] = [];
  for (const m of MOVES[displayName] ?? []) {
    seen.add(m.source);
    out.push(
      withExtra(
        {
          id: `move:${m.source}`,
          label: m.source,
          asPoints: m.asPoints,
          source: "move",
          perLevel: m.perLevel,
          minLevel: m.minLevel,
          maxLevel: m.maxLevel,
        },
        extras[m.source],
      ),
    );
  }
  for (const [source, extra] of Object.entries(extras)) {
    if (seen.has(source)) continue;
    out.push({
      id: `move:${source}`,
      label: source,
      asPoints: extra.asPoints ?? 0,
      source: "move",
      perLevel: extra.perLevel,
      minLevel: extra.minLevel,
      maxLevel: extra.maxLevel,
      statMultipliers: extra.statMultipliers,
      statAdds: extra.statAdds,
      note: extra.note,
    });
  }
  return out;
}

/** Sum the active boosts' points at a level, given which ids are toggled on. */
export function activeAttackSpeedPoints(
  boosts: ActiveBoost[],
  activeIds: Set<string>,
  level: number,
): number {
  return boosts
    .filter((b) => activeIds.has(b.id))
    .reduce((sum, b) => sum + boostPointsAtLevel(b, level), 0);
}

/** Sum additive stat bonuses from toggles that are on and available at this level. */
export function activeStatAdds(
  boosts: ActiveBoost[],
  activeIds: Set<string>,
  level: number,
): Partial<StatBlock> {
  const adds: Partial<StatBlock> = {};
  for (const b of boosts) {
    if (!activeIds.has(b.id) || !b.statAdds) continue;
    if (!boostAvailableAtLevel(b, level)) continue;
    for (const [stat, add] of Object.entries(b.statAdds) as [keyof StatBlock, number][]) {
      adds[stat] = (adds[stat] ?? 0) + add;
    }
  }
  return adds;
}

/**
 * Combined multiplicative stat factors from the active boosts (e.g. X-Attack
 * → { attack: 1.2, spAttack: 1.2 }). Stacking multipliers compound. Returns a
 * factor per affected stat; absent stats are unbuffed (factor 1).
 */
export function activeStatFactors(
  boosts: ActiveBoost[],
  activeIds: Set<string>,
  level: number,
): Partial<Record<keyof StatBlock, number>> {
  const factors: Partial<Record<keyof StatBlock, number>> = {};
  for (const b of boosts) {
    if (!activeIds.has(b.id) || !b.statMultipliers) continue;
    if (!boostAvailableAtLevel(b, level)) continue;
    for (const [stat, mult] of Object.entries(b.statMultipliers) as [keyof StatBlock, number][]) {
      factors[stat] = (factors[stat] ?? 1) * (1 + mult);
    }
  }
  return factors;
}
